blank_issues_enabled: false
contact_links:
  - name: ðŸ“– Documentation
    url: https://github.com/openutau/svs-index/blob/main/README.md
    about: Read the project documentation and contribution guide
